### ISSUE TITLE
Monitoring explorer

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/explorer#158]
Explorer backend was down and we did not notice it (see #157)

**Comment by nlsdfnbch** [comment]
In order to effectively monitor the service, I'll need to know how I know the service is working **from a user's perspective**.

My guess is that the first indicator is a successful GET request to the website. **What other indicators are there that suggest a problem with the service?** Slow response times? Missing services (i.e. db unreachable)? And so on.

**Comment by palango** [comment]
We should check that the frontend and the backend work:
- Frontend is https://explorer.raiden.network
- Backend is https://explorer.raiden.network/json

**Comment by nlsdfnbch** [comment]
Better, but I need your definition of "working". I can monitor Http codes, but what about successful responses with faulty data? Do I need to check for such a thing as well? For example, are there values returned for the backend that must or must not exist? 

On 24 April 2019 10:41:26 CEST, Paul Lange <notifications@github.com> wrote:
>We should check that the frontend and the backend work:
>- Frontend is https://explorer.raiden.network
>- Backend is https://explorer.raiden.network/json
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/raiden-network/explorer/issues/158#issuecomment-486127294

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by palango** [comment]
We don't need to overengineer this.

I'd just check that both answer with a proper 200 code and not check any data format.

**Comment by christianbrb** [comment]
@eorituz has built a simple monitoring
