### ISSUE TITLE
Add Arbitrum testnet

### ISSUE THREAD

**Issue by netcriptus** [raiden-network/explorer#332]
Raiden LC now supports the Arbitrum testnet. We want to have the explorer working with this chain as well.

**Comment by stanislavaba** [comment]
**Context**

Since Raiden now runs on Arbitrum, we want to create an additional explorer for that. It can be a separate explorer with its own address/URL, or we can combine all of the supported networks on one page (we can design a new interface with drop-downs to select the network)

@taleldayekh 
1) What inputs does marketing need to provide to make this happen? And what is the deadline to provide them?
2) Fernando tells me that this task keeps de-prioritizing over something else. Is there a way we can add Manuel to the task so that they can split the workload?  
3) I'm not yet aware of the workflow for such tasks. When can I get the ETA for this? When can we discuss this issue together?

**Comment by taleldayekh** [comment]
This is more involved. We would need to make a decision and tackle [this issue](https://github.com/raiden-network/team/issues/1161) first.

**Comment by netcriptus** [comment]
The new dashboard is now accessible in (https://rinkarby.explorer.raiden.network/)[https://rinkarby.explorer.raiden.network/]

**Comment by taleldayekh** [comment]
> The new dashboard is now accessible in https://rinkarby.explorer.raiden.network/

@netcriptus I don't understand what this is?

**Comment by karlb** [comment]
The arbitrum testnet explorer is running at https://rinkarby.explorer.raiden.network. I also added one for arbitrum-one at https://arbitrum-one.explorer.raiden.network .
