### ISSUE TITLE
What information to display

### ISSUE THREAD

**Issue by palango** [raiden-network/explorer#51]
The current website shows all information which is provided by the backend, some of which might not be interesting or to detailed for the website: http://explorer.raiden.network

In this issue I'd like to collect feedback about what people think is important and what not.

**Comment by pcppcp** [comment]
- do not show info for the tokens that have 0 channels
- tokens should be sorted by channel count, descending
- have filter that won't display certain tokens, i.e. scenario test token is not that important
- add an input to filter/display token by name/address
- network visualisation should at least display token name. Bonus: channel capacity
- network visualisation overflows to the black div at the bottom 
- move network visualisation legend to the top
- node status page would also be neat
- status page could have a little "last activity" info that would show recent network events

**Comment by Dominik1999** [comment]
Great Network Explorer! I like the clean design and that you can see everything at the first view
Specific feedback:
- Maybe you could add a measure that shows how balanced the network is
- Maybe you could add a measure for connectivity in the network 
- Maybe you could add links to the participants with the most open channels, such that people could connect with them
- I would not show different token networks at the beginning, since there will be only one, right?
- I would not show closed and settled channels 

as inspiration: https://1ml.com/statistics

**Comment by palango** [comment]
I think we created follow-ups for all tasks, closing this.
