### ISSUE TITLE
Add more channel infos to visualization popup

### ISSUE THREAD

**Issue by palango** [raiden-network/explorer#91]
From survey:
> When a node is clicked, other than "highlighting" the channels we should also display those channels in a list with other information such as balance? to make the visualization a bit more useful.

**Comment by kelsos** [comment]
@palango for this we don't have balance information but we can show the total deposit information that is already available. though I will have to thing how and where the channel list will appear because I don't think it would be a good idea to add it as part of the svg. 

Maybe it would make more sense of showing the list on the side and only if it is on a big enough screen.

**Comment by palango** [comment]
how would you display it at the side? I'm not really sure how to do this best.

**Comment by kelsos** [comment]
Well I am not sure what the best solution would be either. But I was thinking something along the lines of the following crude mockup.
![image](https://user-images.githubusercontent.com/2269732/46747059-ab985e00-ccb0-11e8-943c-5fb65d95c32f.png)
